spring:
  application:
    name: goals
  datasource:
    url: jdbc:mysql://localhost:3306/finmaster
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8300

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html # http://localhost:8300/swagger-ui/index.html
  use-management-port: false
  show-actuator: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/